# Generated by Django 2.2.7 on 2019-12-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like_num',
            field=models.IntegerField(),
        ),
    ]
