# Generated by Django 2.2.7 on 2019-12-11 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191210_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allblogs',
            name='like_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='allblogs',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
